config/routes.rb
TakeThis::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations"}

  root to: "profiles#index"
  resources :profiles

  namespace :admin do
    root to: "base#index"
    resources :users do
      resources :permissions
    end
  end

 get "/awaiting_confirmation",
  :to => "users#confirmation",
  :as => "confirm_user"

  put "/admin/users/:user_id/permissions",
      :to => "admin/permissions#update",
      :as => :update_user_permissions

end

app/models/permission.rb
class Permission < ActiveRecord::Base
attr_accessor :user, :action, :thing
belongs_to :user
belongs_to :thing, polymorphic: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user

  has_many :permissions, :as => :thing
  def self.viewable_by(user)
    joins(:permissions).where(permissions: { :action => "view", :user_id => user.id })
  end

  def self.for(user)
    user.admin? ? Profile : Profile.viewable_by(user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         :confirmable

  attr_accessor :email, :password, :password_confirmation, :remember_me



  has_many :stories
  has_one :profile
  has_many :permissions

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authorize_admin!

  def index
  end
end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < ApplicationController
  before_filter :find_user

  def index
    @ability= Ability.new(@user)
    @profiles = Profile.all
  end

  def update
    @user.permissions.clear
    params[:permissions].each do |id, permissions|
      project = Profile.find(id)
      permissions.each do |permission, checked|
        Permission.create!(:user => @user,
                           :thing => project,
                           :action => permission)
  end
end
    flash[:notice] = "Permissions updated."
    redirect_to admin_user_permissions_path
  end

private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

before_filter :authorize_admin!

  def index
    @users = User.all(:order => "email")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user], :as => :admin)
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render action: "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @user.skip_reconfirmation!
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update_attributes(params[:user], as: :admin)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been updated."
      render action: "edit"
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end

    redirect_to admin_users_path
  end

private
  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
private

  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authorize_admin!, except: [:index, :show]
  before_filter :authenticate_user!, only: [:index, :show]
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.build(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.for(current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :email, :biography, :age)
    end

    def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end
end

app/controllers/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def resource_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  private :resource_params

  def after_inactive_sign_up_path_for(resource)
    confirm_user_path
  end
end

app/controllers/users_controller.rb
class UserController < ApplicationController
  def confirmation
  end
end

app/helpers/admin/permissions_helper.rb
module Admin::PermissionsHelper
def permissions
    {
      "view" => "View",
      "create tickets" => "Create Tickets",
      "edit tickets" => "Edit Tickets",
      "delete tickets" => "Delete Tickets"
    }
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end

  def authorized?(permission, thing, &block)
    block.call if can?(permission.to_sym, thing) ||
                            current_user.try(:admin?)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UserHelper
end

app/views/admin/permissions/index.html.erb
<h2>Permissions for <%= @user.email %></h2>
<%= form_tag update_user_permissions_path, :method => :put do %>
  <table id='permissions' cellspacing='0'>
    <thead>
      <th>Profiles</th>
      <% permissions.each do |name, text| %>
 <th><%= text %></th>
       <% end %>
     </thead>
     <tbody>
       <% @profiles.each do |profile| %>
         <tr class='<%= cycle("odd", "even") %>'
             id='profile_<%= profile.id %>'>

           <td><%= profile.name %></td>
           <% permissions.each do |name, text| %>
             <td>
               <%= check_box_tag "permissions[#{profile.id}][#{name}]",
                 @ability.can?(name.to_sym, project) %>
             </td>
           <% end %>
         </tr>
       <% end %>
     </tbody>
</table>
   <%= submit_tag "Update" %>
 <% end %>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <%= f.submit %>
  <p>
   <%= f.check_box :admin %>
   <%= f.label :admin, "Is an admin?" %>
  </p>
<% end %>

app/views/admin/users/confirmation.html.erb
<h1>You have signed up successfully.</h1>

Please confirm your account before signing in.

app/views/admin/users/edit.html.erb
<h2>Editing a User</h2>
<%= render "form" %>

app/views/admin/users/index.html.erb
<%= link_to "New User", new_admin_user_path %>
<ul id='users'>
  <% @users.each do |user| %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

app/views/admin/users/new.html.erb
<h2>New User</h2>
<%= render "form" %>

app/views/admin/users/show.html.erb
<h2><%= @user %></h2>
<%= link_to "Edit User", edit_admin_user_path(@user) %>
<%= link_to "Delete User", admin_user_path(@user), :method => :delete, :confirm => "Are you sure you want to delete this user?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Take This</title>
  <!-- If you are using the gem version, you need this only -->
  <link rel="stylesheet" href="css/app.css" />

  <script src="js/vendor/custom.modernizr.js"></script>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
     <% admins_only do %>
      <%= link_to "Admin", admin_root_path %>
    <% end %>

   <% else%>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>
</nav>

<% flash.each do |key, value|%>
<div class='flash' id= '<%= key %>'>
  <%= value %>
</div>
<% end %>

<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Biography</th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.age%></td>
        <td><%= profile.email%></td>
        <td><%= profile.biography %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @profile.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @profile.biography %>
</p>



<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>